Controllers/ConfigurationController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using laui;
using laui.ViewModels;

namespace laui.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly Settings _settings;

        public ConfigurationController(IOptions<Settings> settings)
        {
            _settings = settings.Value;
        }

        public IActionResult Index()
        {
            var model = InitializeModel();
            return View(model);
        }

        public IActionResult Test()
        {
            var model = InitializeModel(true);

            // Test HTTP Data Collector API
            var collector = new LogCollector(_settings.WorkspaceId, _settings.WorkspaceKey);
            var collectorConfigurationValid = collector.WriteTestData();

            // Test Log Search API
            var searcher = new LogSearcher(_settings.TenantId, _settings.ApplicationId, _settings.ApplicationKey, 
                _settings.SubscriptionId, _settings.ResourceGroup, _settings.WorkspaceId, _settings.WorkspaceName);
            var searcherConfigurationValid = searcher.SearchTestRecords();
            
            model.IsValid = collectorConfigurationValid && searcherConfigurationValid;
            return View("Index", model);
        }

        private ConfigurationViewModel InitializeModel(bool isTested = false)
        {
            var model = new ConfigurationViewModel {
                TenantId = _settings.TenantId,
                SubscriptionId = _settings.SubscriptionId,
                ApplicationId = _settings.ApplicationId, 
                ApplicationKey = _settings.ApplicationKey,
                ResourceGroup = _settings.ResourceGroup,
                WorkspaceId = _settings.WorkspaceId,
                WorkspaceKey = _settings.WorkspaceKey,
                WorkspaceName = _settings.WorkspaceName
            };

            if(isTested)
            {
                model.IsTested = isTested;
            }

            return model;
        }
    }
}

Controllers/SearchController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using laui.ViewModels;

namespace laui.Controllers
{
    public class SearchController : Controller
    {
        private readonly Settings _settings;

        public SearchController(IOptions<Settings> settings)
        {
            _settings = settings.Value;
        }

        [HttpGet]
        public IActionResult Events()
        {
            return View(new SearchViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Events(SearchViewModel model)
        {
            // Perform search
            var searcher = new LogSearcher(
                _settings.TenantId,
                _settings.ApplicationId,
                _settings.ApplicationKey, 
                _settings.SubscriptionId,
                _settings.ResourceGroup,
                _settings.WorkspaceId,
                _settings.WorkspaceName);

            model.Records = await searcher.SearchTraceRecords(model.TransactionId, model.VehicleId);
            return View(model);
        }

        [HttpGet]
        public IActionResult Transactions()
        {
            return View(new SearchViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Transactions(SearchViewModel model)
        {
            // Perform search
            var searcher = new LogSearcher(
                _settings.TenantId,
                _settings.ApplicationId,
                _settings.ApplicationKey, 
                _settings.SubscriptionId,
                _settings.ResourceGroup,
                _settings.WorkspaceId,
                _settings.WorkspaceName);

            model.Transactions = await searcher.SearchTransactions(model.TransactionId, model.VehicleId);
            return View(model);
        }
    }
}

Controllers/SeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using laui;
using laui.ViewModels;

namespace laui.Controllers
{
    public class SeedController : Controller
    {
        private readonly Settings _settings;

        public SeedController(IOptions<Settings> settings)
        {
            _settings = settings.Value;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new SeedViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Seed(SeedViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var recordString = RecordFactory.GenerateTraceRecords(
                model.VehicleId,
                model.TotalTransactions, 
                model.BadTransactions.HasValue ? model.BadTransactions.Value : 0);
            
            var collector = new LogCollector(_settings.WorkspaceId, _settings.WorkspaceKey);
            model.IsSuccess = await collector.Collect(Constants.RecordTypeTrace, recordString);
            model.IsSeeded = true;

            return View("Index", model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LA UI - @ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LA UI</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Configuration" asp-action="Index">Configure</a></li>
                    <li><a asp-area="" asp-controller="Seed" asp-action="Index">Seed</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="Events">Trace events</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="Transactions">Trace transactions</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Log Analytics User Interface - &copy; 2017 - Christoph Petersen</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validate">
        </script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validate && window.jQuery.validate.unobtrusive">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>